
name: Benchmark

on:
  workflow_dispatch

# workflow consists of one building and testing job
jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref: ['hdf5','root']
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        ref: ${{matrix.ref}}
    -
      name: Build and Install
      run: |
        source rootless-env.sh
        ldmx config
        ldmx cmake -B build -S .
        ldmx cmake --build build --target install
    -
      name: Run Benchmark
      run: |
        source rootless-env.sh
        ldmx ./.github/workflows/bench.sh 100 1 10 100 1000 10000 100000
    -
      name: Save Benchmark Data
      uses: actions/upload-artifact@v2
      with:
        name: Benchmark-${{matrix.ref}}-${{github.sha}}
        path: data.csv

