
name: Benchmark

on:
  workflow_dispatch:
    inputs:
      n_events_list:
        description: 'Space-separated listing of event numbers to benchmark'
        required: false
        default: '1 10 100 1000 10000 100000'
      n_trials:
        descrption: 'Number of trials per event number to do for benchmark average'
        required: false
        default: 10

# workflow consists of one building and testing job
jobs:
  bench:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: Benchmark
      run: |
        source env.sh
        source Bench/run.sh
        bench ${{github.event.inputs.n_trials}} ${{github.event.inputs.n_events_list}}
    -
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    -
      name: Install Plotting Requirements
      run: python -m pip install --upgrade matplotlib pandas
    -
      name: Plot
      run: |
        python Bench/plot.py data.csv
        mv data.csv *data.pdf *data.png Bench/results/
        git config --global user.name "Bench Bot"
        git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
        git add Bench/results/*
        git commit -m "auto: updated benchmarking results for ${GITHUB_SHA:8}"
        git push
