
name: CI

on:
  push:
    paths:
      - '*'
      - '!*.md'
    branches:
      - '**'
    tags:
      - 'v*.*'

# workflow consists of one building and testing job
jobs:
  test:
    needs: build
    if: ${{needs.build.outputs.test_tag != 'noop'}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Env Script
      uses: actions/checkout@v2
    -
      name: Test the Build
      run: |
        source rootless-env.sh
        ldmx cmake -B build -S .
        cd build
        ldmx make test
