
name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*'
    paths:
      - '**' # on all changes
      - '!**.md' # except markdown files

# workflow consists of one building and testing job
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
        submodules: 'recursive'
    -
      name: Test the Build
      run: |
        source rootless-env.sh
        ldmx cmake -B build -S .
        cd build
        ldmx make
