
name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*'
    paths:
      - '**' # on all changes
      - '!**.md' # except markdown files

# workflow consists of one building and testing job
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: Test the Build
      run: |
        source rootless-env.sh
        echo "::group::Using HDF5"
        ldmx use dev hdf5
        ldmx cmake -B build/hdf5 -S .
        ldmx cmake --build build/hdf5/
        echo "::endgroup::"
        echo "::group::Using ROOT"
        ldmx use dev latest
        ldmx cmake -B build/root -S . -DUSE_ROOT=ON
        ldmx cmake --build build/root/
        echo "::endgroup::"
