
name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*'
    paths:
      - '**' # on all changes
      - '!**.md' # except markdown files

# workflow consists of one building and testing job
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: Test the Build
      run: |
        echo "::group::Init Environment"
        source env.sh
        source Bench/run.sh
        echo "::endgroup::"
        bench 1 10
