
name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*'
    paths:
      - '**' # on all changes
      - '!**.md' # except markdown files

# workflow consists of one building and testing job
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - 
      name: Get Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    -
      name: Test the Build
      run: |
        echo "::group::Init Environment"
        source rootless-env.sh
        echo "::endgroup::"
        echo "::group::Configure Build"
        ldmx cmake -B build -S .
        echo "::endgroup::"
        echo "::group::Build and Install"
        ldmx cmake --build build --target install
        echo "::endgroup::"
        echo "::group::Production Mode"
        ldmx fire produce.py 10
        echo "::endgroup::"
        echo "::group::Recon Mode"
        ldmx fire recon.py output/output_10
        echo "::endgroup::"

